### ISSUE TITLE
Use explicit units

### ISSUE THREAD

**Issue by fred-wang** [fred-wang/TeXZilla#43]
For example linethickness="0" should be linethickness="0px"

**Comment by mazeto** [comment]
Or `linethickness="0.1em"`.

**Comment by fred-wang** [comment]
cc @distler

All unitless length values are discouraged in MathML 3:  "A number without a unit is intepreted as a multiple of the reference value. This form is primarily for backward compatibility and should be avoided, prefering explicit units for clarity. " (https://www.w3.org/TR/MathML3/chapter2.html#fund.units)

However, "0" is likely to be preserved in MathML Core: https://github.com/mathml-refresh/mathml/issues/24 ; still I think it is safe to use "0px" everywhere so I'll land a commit for that.

**Comment by fred-wang** [comment]
> Or `linethickness="0.1em"` for compatibility with hidpi displays.

Using a nonzero value is incorrect, for example the layout of fraction is different depending on whether linethickness is zero or not: https://mathml-refresh.github.io/mathml-core/#mfrac ; also I think some AT rely on that to present fraction differently.
