### ISSUE TITLE
Styling the page

### ISSUE THREAD

**Issue by bl4ckdu5t** [fred-wang/TeXZilla#48]
Would it be fine if I styled this page to be a lot more visual friendly?

**Comment by fred-wang** [comment]
Sure, feel free to submit a PR!

Maybe @rgaiacs can help reviewing and ensure it goes live on https://fred-wang.github.io/TeXZilla/

**Comment by bl4ckdu5t** [comment]
@rgaiacs @fred-wang I tried to not change much and keep the styling as simple as possible. Here's what it looks like:
![screencapture-localhost-8080-1493800883846](https://cloud.githubusercontent.com/assets/5395567/25653773/01f6cc32-2fb4-11e7-984a-d1c36a21bd05.png)
![screencapture-localhost-8080-examples-handleparsingerror-html-1493800946793](https://cloud.githubusercontent.com/assets/5395567/25653826/32131b6e-2fb4-11e7-87b7-c99c97573a4f.png)
![screencapture-localhost-8080-examples-toimage-html-1493801102321](https://cloud.githubusercontent.com/assets/5395567/25653829/34f0bfda-2fb4-11e7-9a9e-f182e8684a2c.png)

**Comment by rgaiacs** [comment]
@bl4ckdu5t Thanks for the screenshots. They looks amazing.

**Comment by bl4ckdu5t** [comment]
Glad you appreciate them.

**Comment by bl4ckdu5t** [comment]
@rgaiacs plans on putting the changes live?

**Comment by rgaiacs** [comment]
@bl4ckdu5t I merged your pull request but I don't know why it didn't update.

**Comment by bl4ckdu5t** [comment]
Thanks @rgaiacs I see it's been merged. I'd have to get the rawgit CDN url of the file in the repo and pass that instead since it returns a 404 for `/style.css`.

**Comment by bl4ckdu5t** [comment]
I corrected that in #51 . You may merge that instead
