### ISSUE TITLE
Merge master and gh-pages

### ISSUE THREAD

**Issue by bl4ckdu5t** [fred-wang/TeXZilla#49]
Was wondering since github now allows any branch to be hosted and the gh-pages is pretty much the same as the master branch. Perhaps it'd be a good idea to have one of these branches deleted (preferrably gh-pages).

**Comment by fred-wang** [comment]
The rule of thumb is to only track non-generated content on the master branch, so I would close this as WONTFIX. gh-pages and release branches have generated content in order to have it available on the web page in the release archive.

**Comment by bl4ckdu5t** [comment]
Okay thanks for clearing that up
