### ISSUE TITLE
Can't resolve system

### ISSUE THREAD

**Issue by m93a** [fred-wang/TeXZilla#53]
I installed TeXZilla using NPM. When I tried to import it, this error appeared:
```
./node_modules/texzilla/TeXZilla.js
Module not found: Can't resolve 'system' in '/home/m93a/Dokumenty/Vývoj/punk-tex/node_modules/texzilla'
```

**Comment by fred-wang** [comment]
Have you figured out the problem with this issue?

Maybe something is broken in recent version of NPM.

**Comment by m93a** [comment]
We just installed `system` by `npm i system` and that was it. Is it possible that TeXZilla is using that but it's not listed in dependencies?

**Comment by fred-wang** [comment]
I just tried with the latest NPM/nodejs version from debian testing and all seem to work. Closing since it seems a system/package bug rather than a TeXZilla bug.

**Comment by johanneswilm** [comment]
@fred-wang I am getting this same error when bundling with webpack. There is also a warning about a missing package "webserver", but if I include the package called "webserver" from npmjs, I receive a lot more errors.
