### ISSUE TITLE
Height of region surrounding the equation

### ISSUE THREAD

**Issue by justineuro** [fred-wang/TeXZilla#54]
How does one change the **height** of the region surrounding a rendered MathML code?

**Comment by justineuro** [comment]
Ended up enclosing the `MathML` within a `<span></span>` tag pair and providing a `style="margin-top: -NNpx; margin-top:-NNpx;"` (with `NN` chosen as appropriate) within the opening tag to decrease the height of formula displayed.

**Comment by fred-wang** [comment]
Yes, this is a pure HTML5 question. Not related to TeXZilla at all.
