### ISSUE TITLE
Tilde for a non-breaking space is not supported

### ISSUE THREAD

**Issue by m93a** [fred-wang/TeXZilla#56]
The tilde character `~` should be treated as a non-breaking space. See the [LaTeX FAQ](https://en.wikibooks.org/wiki/LaTeX/FAQ#Non-breaking_spaces). Original issue: josdejong/mathjs#1299

## Input
```latex
x~y~z
```

## Expected output
```html
<mi>x</mi>
<mspace linebreak="nobreak" width="mediummathspace" />
<mi>y</mi>
<mspace linebreak="nobreak" width="mediummathspace" />
<mi>z</mi>
```

## Actual output
```html
<mi>x</mi>
<mo stretchy="false">~</mo>
<mi>y</mi>
<mo stretchy="false">~</mo>
<mi>z</mi>
```

**Comment by fred-wang** [comment]
TeXZilla follows itex2MML's behavior.

cc' @distler

**Comment by fred-wang** [comment]
Yeah, sorry. Quoting https://github.com/fred-wang/TeXZilla/wiki/TeXZilla-Commands :

"However, note that the LaTeX language is not really a standard in the strict sense. There are many LaTeX commands, macros and packages and new ones are always invented to cover the need of different communities. TeXZilla is intended to remain small and will not support all the imaginable LaTeX commands, even less those used in non-math mode. For a LaTeX-to-XML converter with a very good coverage we recommend to check LaTeXML instead. The reference LaTeX support used by TeXZilla is the one provided by itex2MML, which should cover what the majority of people need to write mathematical formulas."

Of course, your are free to fork/tweak TeXZilla to cover your needs.
