### ISSUE TITLE
Broken links to Three.js in MathML in WebGL

### ISSUE THREAD

**Issue by pepelsbey** [fred-wang/TeXZilla#75]
[The demo](https://fred-wang.github.io/TeXZilla/examples/toImageWebGL.html) currently hotlinks to Three.js’ website that doesn’t host library files anymore:

```html
<script src="https://threejs.org/build/three.min.js" type="text/javascript"></script>
<script src="https://threejs.org/examples/js/controls/OrbitControls.js" type="text/javascript"></script>
```

I’d suggest using the new ones they recommend in docs:

- https://cdn.jsdelivr.net/npm/three@0.168.0/build/three.module.min.js
- https://cdn.jsdelivr.net/npm/three@0.168.0/examples/jsm/controls/OrbitControls.min.js

However, I couldn’t quickly make it work by just swapping the URLs.

**Comment by fred-wang** [comment]
@pepelsbey Thanks it should be working again now. Can you please confirm?

(probably TeXZilla should be proposed a JS module, I've opened https://github.com/fred-wang/TeXZilla/issues/76)

**Comment by pepelsbey** [comment]
Works great now! Thanks :)
