### ISSUE TITLE
Mistake in the formula

### ISSUE THREAD

**Issue by jido** [fred-wang/TeXZilla#78]
In example six, there is an application of the half-angle formula which is not correct. The result is correct but that's only because sin(π/6) = 1/2.

The actual formula is tan(a) = (1 - cos(2a)) / sin(2a).

https://github.com/fred-wang/TeXZilla/blob/4f5daba7461ec98a312863d11ddf99008589cad1/examples/customElement.html#L348

**Comment by fred-wang** [comment]
@jido Thank you for the report. Do you plan to submit a PR?

**Comment by jido** [comment]
Fine, I did that.

**Comment by jido** [comment]
When will it update at:

http://fred-wang.github.io/TeXZilla/examples/customElement.html
?

**Comment by fred-wang** [comment]
I just merged into the gh-pages branch, so that should happen soon.
